#!/usr/bin/env python


import os
import sys
import getopt

class #script_classname
    def __init__(self):
        pass
        

def print_help():
    print """
    #script_name:
    
    """  
    
if __name__ == "__main__":
    try:
        opts, args = getopt.gnu_getopt( sys.argv[1:], "h", ["help"] )
    except getopt.GetoptError:
        print "I didn't understand some options you gave..."
        print_help()
        sys.exit( 2 )

    for o, a in opts:
        if o in ( "-h", "--help" ):
            print_help()  
            sys.exit(0)
    
    cobj = #script_classname()